export const APP_NAME = '#ARIVU'
export const WEATHER_ICON_PATH = 'http://openweathermap.org/img/wn/'
export const COUNTRIES = [
    {
        name:'Arabic',
        code:'ar'
    },
    {
        name:'German',
        code:'de'
    },
    {
        name:'English',
        code:'en'
    },
    {
        name:'Spanish',
        code:'es'
    },
    {
        name:'French',
        code:'fr'
    },
    {
        name:'Hebrew',
        code:'he'
    },
    {
        name:'Italian',
        code:'it'
    },
    {
        name:'Dutch',
        code:'nl'
    },
    {
        name:'Norwegian',
        code:'no'
    },
    {
        name:'Portuguese',
        code:'pt'
    },
    {
        name:'Russian',
        code:'ru'
    },
    {
        name:'Northern Sami',
        code:'se'
    },
    {
        name:'ud',
        code:'ud'
    },
    {
        name:'Chinese',
        code:'zh'
    },
]
export const SORT_BY = [
    {
        name:'Published Date',
        code:'publishedAt'
    },
    {
        name:'Relevant',
        code:'relevancy'
    },
    {
        name:'Popular',
        code:'popularity'
    },
]